### ISSUE TITLE
Test the new trained model with validation dataset

### ISSUE THREAD

**Issue by marcdalangin** [marcdalangin/thesis-final#5]
Test the 'revised_model-date.h5' with the new validation dataset in test_model.py

**Comment by catherenereyes** [comment]
Done.
![Screenshot 2023-09-20 144203](https://github.com/marcdalangin/thesis-final/assets/114873125/6c66eb1a-99db-4939-8faf-f9d55669bb0e)

**Comment by catherenereyes** [comment]
![Screenshot 2023-09-20 144203](https://github.com/marcdalangin/thesis-final/assets/114873125/fa01a430-9158-4165-b622-c3d2438e7945)

**Comment by marcdalangin** [comment]
Provide atleast 5 sets of 10 images  sa testing. Kahit random images from iba't ibang categories provided na wala yung mga image na yun sa training_dataset @catherenereyes

**Comment by catherenereyes** [comment]
Error Found: 

2023-09-21 17:51:35.528643: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE SSE2 SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[ WARN:0@0.095] global loadsave.cpp:244 cv::findDecoder imread_('validation_dataset/5/IMG_4450.JPG'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "c:\Users\My PC\Downloads\thesis-final-master (1)\thesis-final-master\test_model.py", line 67, in <module>
    user_input_images = [cv2.resize(image, (28, 28)) for image in user_input_images]
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\My PC\Downloads\thesis-final-master (1)\thesis-final-master\test_model.py", line 67, in <listcomp>
    user_input_images = [cv2.resize(image, (28, 28)) for image in user_input_images]
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4062: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

Line 67: 

user_input_images = [cv2.resize(image, (28, 28)) for image in user_input_images]

**Comment by catherenereyes** [comment]
[Testing.docx](https://github.com/marcdalangin/thesis-final/files/12684451/Testing.docx)
